[colors.primary]
background = '#070102'
foreground = '#D12E1A'

[colors.cursor]
text = '#D12E1A'
cursor = '#724A41'

[colors.normal]
black   = '#070102'
red     = '#2E0406'
green   = '#4F080A'
yellow  = '#6F0C0D'
blue    = '#392221'
magenta = '#9F1813'
cyan    = '#6B2925'
white   = '#D12E1A'

[colors.bright]
black   = '#724A41'
red     = '#A85544'
green   = '#E45430'
yellow  = '#E86F4B'
blue    = '#D87B82'
magenta = '#F0945E'
cyan    = '#E5BC6E'
white   = '#F5E0B0'
