#!/bin/bash

path=~/.cache/shwal/colors

# Ensure shwal colors are available
if [ ! -f $path ]; then
    echo "Please run wal to generate colors first."
    exit 1
fi

# Get colors from pywal
bg_color=$(sed -n '1p' $path)
fg_color=$(sed -n '2p' $path)
selected_bg=$(sed -n '3p' $path)
selected_fg=$(sed -n '4p' $path)

# Run dmenu with pywal colors
dmenu -nb "$bg_color" -nf "$fg_color" -sb "$selected_bg" -sf "$selected_fg" -fn "Mononoki Nerd Font-12" "$@"
