#!/usr/bin/env bash

# Options
shutdown=' Shutdown'
reboot=' Reboot'
lock=' Lock'
suspend=' Suspend'
logout=' Logout'
yes=' Yes'
no=' No'

# Menu command based on $MENU variable
menu_cmd() {
    dm-shwal -p "powermenu:" -i
}

# Confirmation CMD
confirm_cmd() {
    dm-shwal -p "Are you sure?" -i
}

# Ask for confirmation
confirm_exit() {
    echo -e "$yes\n$no" | confirm_cmd
}

# Pass variables to dmenu
run_menu() {
    echo -e "$logout\n$reboot\n$shutdown" | menu_cmd
}

# Execute Command
run_cmd() {
    selected="$(confirm_exit)"
    sleep 1
    if [[ "$selected" == "$yes" ]]; then
        if [[ $1 == '--shutdown' ]]; then
            systemctl poweroff
        elif [[ $1 == '--reboot' ]]; then
            systemctl reboot
        elif [[ $1 == '--logout' ]]; then
            pkill -KILL -u "$USER"
        fi
    else
        exit 0
    fi
}

# Actions
chosen="$(run_menu)"
case ${chosen} in
    $shutdown)
        run_cmd --shutdown
        ;;
    $reboot)
        run_cmd --reboot
        ;;
    $logout)
        run_cmd --logout
        ;;
esac
