#!/usr/bin/env bash

# Current Theme
rofi_theme="$HOME/.config/rofi/powermenu/config.rasi"
rofi_alignment='linear' # linear / vertical

# Options
shutdown=' Shutdown'
reboot=' Reboot'
lock=' Lock'
suspend=' Suspend'
logout=' Logout'
yes=' Yes'
no=' No'

# Menu command based on $MENU variable
menu_cmd() {
    if [[ "$MENU" == "dmenu" ]]; then
        dmenu_shwal -p "powermenu:" -i
    else
        rofi -dmenu -theme $rofi_path -i
    fi
}

# Confirmation CMD
confirm_cmd() {
    if [[ "$MENU" == "dmenu" ]]; then
        dmenu_shwal -p "Are you sure?" -i
    else
        rofi -theme-str 'window {location: center; anchor: center; fullscreen: false; width: 250px;}' \
            -theme-str 'mainbox {children: [ "message", "listview" ];}' \
            -theme-str 'listview {columns: 2; lines: 1;}' \
            -theme-str 'element-text {horizontal-align: 0.5;}' \
            -theme-str 'textbox {horizontal-align: 0.5;}' \
            -dmenu -p 'Confirmation' -mesg 'Are you Sure?' -theme $rofi_theme
    fi
}

# Ask for confirmation
confirm_exit() {
    echo -e "$yes\n$no" | confirm_cmd
}

# Pass variables to rofi/dmenu
run_menu() {
    echo -e "$logout\n$reboot\n$shutdown" | menu_cmd
}

# Execute Command
run_cmd() {
    selected="$(confirm_exit)"
    sleep 1
    if [[ "$selected" == "$yes" ]]; then
        if [[ $1 == '--shutdown' ]]; then
            systemctl poweroff
        elif [[ $1 == '--reboot' ]]; then
            systemctl reboot
        elif [[ $1 == '--logout' ]]; then
            pkill -KILL -u "$USER"
        fi
    else
        exit 0
    fi
}

# Actions
chosen="$(run_menu)"
case ${chosen} in
    $shutdown)
        run_cmd --shutdown
        ;;
    $reboot)
        run_cmd --reboot
        ;;
    $logout)
        run_cmd --logout
        ;;
esac
