#!/bin/bash

pkgs() {
    echo `pacman -Qq | wc -l`
}

bri() {
    echo `brightnessctl | grep '%' | awk '{print $4}' | sed 's/(//g' | sed 's/)//g'`
}

vol() {
    echo `pamixer --get-volume-human`
}

upt() {
    upt="$(uptime --pretty | sed -e 's/up //g' -e 's/ days/d/g' -e 's/ day/d/g' -e 's/ hours/h/g' -e 's/ hour/h/g' -e 's/ minutes/m/g' -e 's/, / /g')"
    echo -e "$upt"
}

batry() {
    if [ "$(echo "$(acpi 2>&1)" | grep 'No support')" ]; then
        echo "power supply"
    else
        echo "$(acpi 2>&1 | awk '{print $4}' | cut -d ',' -f1)"
    fi
}

ker() {
    echo `uname -sr`
}

dt() {
    echo `date | awk '{print $2" "$3" "$6" ("$1")"}'`
}

tm() {
    echo `date | awk '{print $4}'`
}

wifi() {
    if [[ "$(iwgetid -r)" ]]; then
        echo "$(iwgetid -r) [CONNECTED]"
    else
        echo "Offline"
    fi
}

ethernet() {
    if [[ "$(nmcli | grep 'connected to Wired connection')" ]]; then
        echo "Ethernet [CONNECTED]"
    else
        echo "Offline"
    fi
}

while getopts "lvubhkdtwep" obj; do
    case "${obj}" in
        l)
            bri;;
        v)
            vol;;
        u)
            upt;;
        b)
            batry;;
        k)
            ker;;
        d)
            dt;;
        t)
            tm;;
        w)
            wifi;;
        e)
            ethernet;;
        p)
            pkgs;;
        h | *)
            echo "empty";;
    esac
done
